### PR TITLE
Fix LSP server for unsaved files on Windows.

### LINKED ISSUE #183: LSP server doesn't work for unsaved files on Windows
If a file has never been saved, then the LSP server on Windows doesn't work.

### PR DESCRIPTION
**Pull request by floitsch**
A virtual file is starting with '///'. When converting from compiler
paths to local paths, the language server would convert the slashes to
backslashes thus giving it a new name.

Fixes #183.

### CODE REVIEW

File: tools/toitlsp/lsp/compiler/path/path.go [hunk 1]
```diff
@@ -21,6 +21,14 @@ import (
 	"strings"
 )
 
+const (
```
Comment (floitsch) [inline tools/toitlsp/lsp/compiler/path/path.go:24]: This is currently duplicated from uri/convert.go, but Go doesn't allow cyclic imports, so removing the duplication would require a refactoring.
I might do it in a follow-up PR.

**Review by kasperl — APPROVED** [review]
Looks good to me.
