### PR TITLE
Don't chop up UTF-8 byte sequences in messages

### LINKED ISSUE #1322: Error messages have issues with utf8
It looks like we are cutting strings at non-utf8 locations, and then try to convert the result to strings again.
This happens when we send error messages.

```
import expect show *

main:
  expect_equals """
    ╒════╤════════╕
    │ no   header │
    ╘════╧════════╛
    """
    """
    ┌────┬────────┐
    │ no   header │
    └────┴────────┘
    """
```

leads to:

```
ᐅ toit.run ~/tmp/bad.toit
: Expected <╒════╤════════╕
│ no   header │
╘════╧════════╛
>, but was <┌────┬────────┐
│ no   header │
└────┴────────┘
>
----
Received a Toit system message. Executing the command below will
make it human readable:
----
jag decode WyNVBVVYU1UPdjIuMC4wLWFscGhhLjQ2U1UAWyRVI1UQd+aCRXdwUTSpohAzBX3IAlsjVQRVRVNVEEFTU0VSVElPTl9GQUlMRURTVWtFeHBlY3RlZCA84pWS4pWQ4pWQ4pWQ4pWQ4pWk4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWVCuKUgiBubyAgIGhlYWRlciDilIIK4pWY4pWQ4pWQ4pWQ4pWQ4pWn4pWQ4pWQ4pWQ4i4uLlsjVQJVU1sjVQ1bI2wAAAADVUZVAEkFq1sjbAAAAANVRlUBSQXCWyNsAAAAA1VGVQJJBXBbI2wAAAADVUZVA0kBTFsjbAAAAANVRlUESQGSWyNsAAAAA1VGVQVV+1sjbAAAAANVRlUGSQRVWyNsAAAAA1VGVQdJBatbI2wAAAADVUZVCEkFwlsjbAAAAANVRlUJSQVwWyNsAAAAA1VGVQpJHQpbI2wAAAADVUZVC0kdH1sjbAAAAANVRlUMSQRy
```

Note that it doesn't show a stack trace, but a jag decode.

Trying to run it with `system_message` shows that we hit an invalid UTF8:
```
toit.run ~/code/opentoit/tools/system_message.toit --message=WyNVBVVYU1UPdjIuMC4wLWFscGhhLjQ2U1UAWyRVI1UQd+aCRXdwUTSpohAzBX3IAlsjVQRVRVNVEEFTU0VSVElPTl9GQUlMRURTVWtFeHBlY3RlZCA84pWS4pWQ4pWQ4pWQ4pWQ4pWk4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWVCuKUgiBubyAgIGhlYWRlciDilIIK4pWY4pWQ4pWQ4pWQ4pWQ4pWn4pWQ4pWQ4pWQ4i4uLlsjVQJVU1sjVQ1bI2wAAAADVUZVAEkFq1sjbAAAAANVRlUBSQXCWyNsAAAAA1VGVQJJBXBbI2wAAAADVUZVA0kBTFsjbAAAAANVRlUESQGSWyNsAAAAA1VGVQVV+1sjbAAAAANVRlUGSQRVWyNsAAAAA1VGVQdJBatbI2wAAAADVUZVCEkFwlsjbAAAAANVRlUJSQVwWyNsAAAAA1VGVQpJHQpbI2wAAAADVUZVC0kdH1sjbAAAAANVRlUMSQRy
ILLEGAL_UTF_8
```

### PR DESCRIPTION
**Pull request by erikcorry**
Fixes #1322

### CODE REVIEW

File: src/encoder.cc [hunk 1]
```diff
@@ -50,8 +50,15 @@ class EncodeVisitor : public Visitor {
...
     String::Bytes bytes(string);
     const char* OVERFLOW_DOTS = "...";
-    const int printed = Utils::min(bytes.length(), MAX_NOF_STRING_ELEMENTS);
-    const bool overflow = bytes.length() > MAX_NOF_STRING_ELEMENTS;
+    int printed = bytes.length();
+    const bool overflow = printed > MAX_NOF_STRING_ELEMENTS;
+    if (overflow) {
+      printed = MAX_NOF_STRING_ELEMENTS;
+      // Don't chop up UTF-8 sequences.
+      while ((bytes.at(printed) & ~Utils::UTF_8_MASK) == Utils::UTF_8_PAYLOAD && printed > 0) {
```
Comment (floitsch) [inline src/encoder.cc:58]: I don't really like the check for `printed > 0`.
How can that even happen?

File: tests/negative/unicode_expect_failure_test.toit [hunk 2]
```diff
@@ -0,0 +1,13 @@
+import expect show *
```
Comment (floitsch) [inline tests/negative/unicode_expect_failure_test.toit:1]: Add a copyright.

Also add a comment, what this test is for. (refer to the issue, and a small explanation).

**Review by floitsch — APPROVED** [review]
LGTM.
